'use strict';
// Original synthesised sounds; no downloads or third-party recordings.
window.CarSounds=(()=>{
let context,master,engine,engineGain,enabled=true;
function unlock(){try{if(!context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return false;context=new Audio();master=context.createGain();master.gain.value=enabled?.22:0;master.connect(context.destination);engine=context.createOscillator();engine.type='triangle';engineGain=context.createGain();engineGain.gain.value=0;engine.connect(engineGain);engineGain.connect(master);engine.start()}if(context.state==='suspended')context.resume().catch(()=>{});return true}catch{return false}}
function tone(frequency,duration=.15,delay=0,type='sine',end=frequency,volume=.3){if(!context||!enabled||context.state!=='running')return;const t=context.currentTime+delay,o=context.createOscillator(),g=context.createGain();o.type=type;o.frequency.setValueAtTime(frequency,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect()}}
function effect(name){if(!enabled)return;const notes={start:[392,523,784],finish:[523,659,784,1047,1319],swim:[330,440,550],glide:[392,587,880],pass:[659,880]};if(notes[name])notes[name].forEach((f,i)=>tone(f,.22,i*.11,'sine',f,.32));else if(name==='jump')tone(230,.28,0,'sine',850,.42);else if(name==='trap'){tone(160,.22,0,'triangle',55,.5);tone(360,.1,.06,'sine',90,.2)}else if(name==='pick')tone(660,.09,0,'sine',880,.2)}
return {unlock,effect,setEnabled(value){enabled=value;if(master)master.gain.setTargetAtTime(enabled?.22:0,context.currentTime,.025)},engine(speed){if(!context)return;engine.frequency.setTargetAtTime(48+speed*5,context.currentTime,.1);engineGain.gain.setTargetAtTime(enabled&&speed>.1?.12:0,context.currentTime,.06)},stop(){if(engineGain)engineGain.gain.setTargetAtTime(0,context.currentTime,.02)}};
})();
