'use strict';
(()=>{
const $=id=>document.getElementById(id), STORAGE='car-drivers-v1';
const colours={Red:'#e86a62',Orange:'#ec9c55',Yellow:'#edcd60',Green:'#91bb75',Blue:'#7cafd0',Purple:'#ad8cc4',Pink:'#ef7895'};
const levels=[{name:'Original',distance:400,icon:'⌁',description:'A sunny first drive.',trophy:'First wheels',theme:'green'},{name:'Jiggly Road',distance:600,icon:'〰',description:'Little bumps. Big adventure.',trophy:'Bumpy road star',theme:'green'},{name:'Rainbow Road',distance:800,icon:'🌈',description:'Follow a road full of colour.',trophy:'Rainbow champion',theme:'rainbow'},{name:'Lakeside Splash',distance:1000,icon:'≈',description:'Make a splash. Try swim mode.',trophy:'Splash superstar',theme:'lake'},{name:'Sky Adventure',distance:1200,icon:'♢',description:'Spread your kite and glide.',trophy:'Sky legend',theme:'sky'}];
const cleanName=value=>typeof value==='string'?value.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,20)||'Driver':'Driver';
const escapeHTML=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved={driverName:'Driver',colour:'Pink',tyre:'classic',kite:'diamond',won:[],sound:true,bests:{}};
try{const data=JSON.parse(localStorage.getItem(STORAGE));if(data&&typeof data==='object'){saved.driverName=cleanName(data.driverName);if(typeof data.sound==='boolean')saved.sound=data.sound;if(data.bests&&typeof data.bests==='object')for(let i=0;i<5;i++){const b=data.bests[i];if(b&&Number.isInteger(b.rank)&&b.rank>=1&&b.rank<=4&&Number.isFinite(b.time)&&b.time>0)saved.bests[i]={rank:b.rank,time:b.time}}if(colours[data.colour])saved.colour=data.colour;if(['classic','bumpy','flower'].includes(data.tyre))saved.tyre=data.tyre;if(['diamond','parachute'].includes(data.kite))saved.kite=data.kite;if(Array.isArray(data.won))saved.won=[...new Set(data.won.filter(x=>Number.isInteger(x)&&x>=0&&x<5))]}}catch{$('save-note').hidden=false}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(saved))}catch{$('save-note').hidden=false}}
const sounds=window.CarSounds;
const nameInputs=[$('driver-name'),$('race-driver-name')];
nameInputs.forEach(input=>{input.value=saved.driverName;input.addEventListener('input',()=>{saved.driverName=cleanName(input.value);nameInputs.filter(other=>other!==input).forEach(other=>other.value=input.value);save()});input.addEventListener('blur',()=>{input.value=saved.driverName})});

function soundButtons(){document.querySelectorAll('[data-sound]').forEach(b=>{b.textContent=saved.sound?'♫ Sound on':'♪ Sound off';b.setAttribute('aria-pressed',String(saved.sound))});sounds.setEnabled(saved.sound)}
document.querySelectorAll('[data-sound]').forEach(b=>b.onclick=()=>{saved.sound=!saved.sound;soundButtons();if(saved.sound){sounds.unlock();sounds.effect('pick')}save()});soundButtons();
const ordinal=n=>['1st','2nd','3rd','4th'][n-1];const formatTime=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function standings(){return [{name:race.driverName,isPlayer:true,distance:race.distance,finishTime:race.finishTime,colour:colours[saved.colour]},...race.rivals].sort((a,b)=>{if(a.finishTime!==null&&b.finishTime!==null)return a.finishTime-b.finishTime;if(a.finishTime!==null)return -1;if(b.finishTime!==null)return 1;return b.distance-a.distance})}
let screen='garage',race=null,keys=new Set(),stick={x:0,y:0,pointer:null},lastTime=0,messageUntil=0;
function release(){keys.clear();stick.x=stick.y=0;stick.pointer=null;$('stick').style.transform=''}
function show(name){screen=name;document.querySelectorAll('.screen').forEach(el=>el.hidden=el.id!==name);release();if(name!=='play'&&race){race.running=false;sounds.stop()}window.scrollTo(0,0);if(name==='garage')drawPreview();if(name==='levels')renderLevels();if(name==='collection')renderTrophies()}
function say(text,seconds=2.5){$('game-message').textContent=text;messageUntil=performance.now()+seconds*1000}
function trophy(i){return `<svg viewBox="0 0 240 190" role="img" aria-label="${levels[i].trophy} trophy"><g transform="translate(${35-i*6} ${30-i*4}) scale(${.7+i*.075})"><path d="M64 35H32Q26 91 79 98M136 35H168Q174 91 121 98" fill="none" stroke="#b9853c" stroke-width="12"/><path d="M57 24H143L134 83Q128 108 100 111Q72 108 66 83Z" fill="${['#cd955e','#eac260','#f2cb5a','#f1c951','#f7ce4a'][i]}" stroke="#9e742f" stroke-width="3"/><path d="M100 111v27M77 142h46" stroke="#ad8135" stroke-width="12"/><rect x="61" y="148" width="78" height="20" rx="5" fill="#43674d"/>${i>0?'<text x="100" y="77" text-anchor="middle" font-size="30" fill="#fff4b8">★</text>':''}${i>1?'<path d="M58 105l10 30 17-10M142 105l-10 30-17-10" fill="none" stroke="#df829c" stroke-width="10"/>':''}${i>2?'<path d="M81 145l9-10 10 10-10 10Z M102 145l9-10 10 10-10 10Z" fill="#7cb7dc"/>':''}${i>3?'<path d="M65 12L60-6l25 9L100-17 115 3 140-6 135 12Z" fill="#efbb36" stroke="#9e742f" stroke-width="3"/><text x="5" y="40" font-size="25" fill="#dbaa36">✦</text><text x="179" y="40" font-size="25" fill="#dbaa36">✦</text>':''}</g></svg>`}
function renderLevels(){$('trophy-count').textContent=`${saved.won.length} / 5`;$('level-list').innerHTML=levels.map((l,i)=>`<button class="level-card ${saved.won.includes(i)?'done':''}" data-level="${i}"><small>LEVEL ${i+1} ${saved.won.includes(i)?'· 🏆':''}</small><span class="scene-icon">${l.icon}</span><b>${l.name}</b><span>${l.distance.toLocaleString()} m · ${l.description}</span></button>`).join('');$('level-list').querySelectorAll('button').forEach(b=>b.onclick=()=>start(Number(b.dataset.level)))}
function renderTrophies(){$('trophy-list').innerHTML=levels.map((l,i)=>`<div class="trophy-card ${saved.won.includes(i)?'':'locked'}">${trophy(i)}<b>${l.trophy}</b><p>${saved.won.includes(i)?'✓ Earned':`Finish level ${i+1} to earn`}</p></div>`).join('')}
Object.entries(colours).forEach(([name,hex])=>{const b=document.createElement('button');b.className='swatch';b.style.setProperty('--swatch',hex);b.setAttribute('aria-label',name);b.onclick=()=>{saved.colour=name;customise()};b.dataset.colour=name;$('colours').append(b)});
function customise(){document.querySelectorAll('[data-colour],[data-tyre],[data-kite]').forEach(b=>{const kind=Object.keys(b.dataset)[0];b.setAttribute('aria-pressed',String(saved[kind]===b.dataset[kind]))});$('colour-name').textContent=saved.colour;save();drawPreview();sounds.effect('pick')}
document.querySelectorAll('[data-tyre],[data-kite]').forEach(b=>b.onclick=()=>{const kind=Object.keys(b.dataset)[0];saved[kind]=b.dataset[kind];customise()});
$('choose-road').onclick=()=>show('levels');$('back-garage').onclick=()=>show('garage');$('trophies-button').onclick=()=>{if(screen==='play')pause();show('collection')};$('collection-back').onclick=()=>show('levels');$('race-again').onclick=()=>start(race.index);$('finish-levels').onclick=()=>show('levels');$('next-level').onclick=()=>race.index<4?start(race.index+1):show('collection');
function hazardsFor(index){const result=[];for(let n=0,x=32;x<levels[index].distance-20;n++,x+=index===0?34:27){result.push({x,lane:(n*7+index)%3,type:index===3?(n%3?'water':'mud'):index===4?(n%2?'mud':'water'):index===1?(n%2?'bump':'mud'):n%3===0?'water':'mud',hit:false})}return result}
function start(index){race={index,driverName:saved.driverName,distance:0,lane:1,speed:0,running:false,jump:0,swim:false,glide:false,energy:100,slow:0,hazards:hazardsFor(index),finished:false,elapsed:0,finishTime:null,rivals:[{name:'Pip',colour:'#ec9c55',lane:0,pace:10.8},{name:'Ziggy',colour:'#7cafd0',lane:2,pace:11.5},{name:'Nova',colour:'#ad8cc4',lane:1.75,pace:12.1}].map((b,i)=>({...b,distance:0,finishTime:null,speed:0,slow:0,pace:b.pace+index*.18,seen:new Set(),seed:i}))};show('play');$('level-title').textContent=`${index+1} · ${levels[index].name}`;$('race-name-field').hidden=false;$('race-driver-name').value=saved.driverName;$('overlay-title').textContent='Ready for an adventure?';$('overlay-copy').textContent='Hold the joystick right (or → / D) to drive. Move up and down to steer around traps. Race Pip, Ziggy and Nova! Traps slow every car down. Finish in any position to earn your trophy.';$('resume').textContent='Let’s drive →';$('overlay').hidden=false;updateHUD();drawGame()}
function pause(){if(!race||race.finished||screen!=='play')return;race.running=false;sounds.stop();release();$('race-name-field').hidden=true;$('overlay-title').textContent='Taking a little break';$('overlay-copy').textContent='Your car is waiting right here.';$('resume').textContent='Keep driving →';$('overlay').hidden=false}
$('pause').onclick=pause;$('resume').onclick=()=>{if(race.elapsed===0)race.driverName=saved.driverName;release();sounds.unlock();if(race.elapsed===0)sounds.effect('start');race.running=true;$('overlay').hidden=true;$('game').focus({preventScroll:true});say('Hold right to drive. Up and down to steer.',4)};$('exit-level').onclick=()=>show('levels');
function jump(){if(race?.running&&race.jump===0&&!race.glide){race.jump=.95;sounds.effect('jump');say('Hop over those traps!')}}
function swim(){if(!race?.running)return;race.swim=!race.swim;sounds.effect('swim');if(race.swim)race.glide=false;say(race.swim?'Swim mode: puddles won’t slow you down.':'Back on your wheels.');updateHUD()}
function glide(){if(!race?.running)return;if(race.glide){race.glide=false}else if(race.energy>=25){race.glide=true;sounds.effect('glide');race.swim=false;race.jump=0;say('Gliding! Watch your energy.')}else say('Let your glide energy recharge.');updateHUD()}
function actionButton(id,action){const button=$(id);button.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();action()});button.addEventListener('click',e=>{if(e.detail===0)action()})}actionButton('jump',jump);actionButton('swim',swim);actionButton('glide',glide);
const joy=$('joystick');function moveStick(e){const rect=joy.getBoundingClientRect(),r=rect.width*.33;let x=(e.clientX-rect.left-rect.width/2)/r,y=(e.clientY-rect.top-rect.height/2)/r;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}stick.x=x;stick.y=y;$('stick').style.transform=`translate(${x*r}px,${y*r}px)`}
joy.addEventListener('pointerdown',e=>{if(!race?.running||stick.pointer!==null)return;stick.pointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveStick(e);e.preventDefault()});joy.addEventListener('pointermove',e=>{if(stick.pointer===e.pointerId)moveStick(e)});function endStick(e){if(e.pointerId===stick.pointer){stick.x=stick.y=0;stick.pointer=null;$('stick').style.transform=''}}joy.addEventListener('pointerup',endStick);joy.addEventListener('pointercancel',endStick);joy.addEventListener('lostpointercapture',endStick);
const driveKeys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','a','d','w','s',' ','e','g','Escape'];document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea'))return;if(screen!=='play'||!driveKeys.includes(e.key))return;if(e.target.closest('button')&&(e.key===' '||e.key==='Enter'))return;e.preventDefault();if(e.key==='Escape'){pause();return}if(!race?.running)return;keys.add(e.key);if(!e.repeat){if(e.key===' ')jump();if(e.key==='e')swim();if(e.key==='g')glide()}});document.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{release();if(screen==='play'&&race?.running)pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&race?.running)pause()});
function updateHUD(){if(!race)return;const l=levels[race.index];const order=standings(),rank=order.findIndex(b=>b.isPlayer)+1;$('position').textContent=ordinal(rank)+' / 4';$('race-clock').textContent=formatTime(race.elapsed);$('leader-gap').textContent=rank===1?'You’re leading!':Math.ceil(order[0].distance-race.distance)+' m behind '+order[0].name;$('distance').textContent=`${Math.floor(race.distance)} / ${l.distance.toLocaleString()} m`;$('progress').value=race.distance/l.distance*100;$('energy').value=race.energy;$('swim').setAttribute('aria-pressed',String(race.swim));$('glide').setAttribute('aria-pressed',String(race.glide));$('jump').disabled=race.jump>0||race.glide}
function finish(){race.finishTime=race.elapsed;const order=standings(),rank=order.findIndex(b=>b.isPlayer)+1,old=saved.bests[race.index];if(!old||rank<old.rank||(rank===old.rank&&race.elapsed<old.time))saved.bests[race.index]={rank,time:race.elapsed};save();sounds.stop();sounds.effect('finish');$('podium').innerHTML=order.map((b,i)=>`<div class="podium-place ${b.isPlayer?'is-you':''}"><strong>${ordinal(i+1)}</strong><b>${escapeHTML(b.name)}</b><span>${b.finishTime!==null?formatTime(b.finishTime):'Still racing'}</span></div>`).join('');$('personal-best').textContent=`Your best: ${ordinal(saved.bests[race.index].rank)} · ${formatTime(saved.bests[race.index].time)}`;race.finished=true;race.running=false;if(!saved.won.includes(race.index)){saved.won.push(race.index);save()}$('trophy-count').textContent=`${saved.won.length} / 5`;$('finish-label').textContent=`LEVEL ${race.index+1} COMPLETE · ${levels[race.index].distance.toLocaleString()} M`;$('won-trophy').innerHTML=trophy(race.index);$('finish-title').textContent=rank===1?`${race.driverName}, you won!`:`${race.driverName} finished ${ordinal(rank)}!`;$('finish-copy').textContent=`${levels[race.index].trophy} earned in ${formatTime(race.elapsed)}. ${rank===1?'Brilliant driving!':'Try another race and chase first place!'}`;$('next-level').textContent=race.index===4?'See my trophies →':'Next adventure →';show('finish')}
function update(dt){if(!race?.running)return;const r=race;r.elapsed+=dt;for(const b of r.rivals){if(b.finishTime!==null)continue;b.slow=Math.max(0,b.slow-dt);const targetLane=(Math.floor((b.distance+12)/45)+b.seed)%3;b.lane+=Math.sign(targetLane-b.lane)*Math.min(Math.abs(targetLane-b.lane),dt*.5);b.speed+=(b.pace*(b.slow>0?.4:1)-b.speed)*Math.min(1,dt*3);b.distance=Math.min(levels[r.index].distance,b.distance+b.speed*dt);for(let j=0;j<r.hazards.length;j++){const h=r.hazards[j];if(!b.seen.has(j)&&Math.abs(h.x-b.distance)<2.5&&Math.abs(h.lane-b.lane)<.42){b.seen.add(j);b.slow=1.7}}if(b.distance>=levels[r.index].distance)b.finishTime=r.elapsed}r.jump=Math.max(0,r.jump-dt);r.slow=Math.max(0,r.slow-dt);if(r.glide){r.energy=Math.max(0,r.energy-dt*21);if(r.energy===0){r.glide=false;say('Time to land. Your kite is recharging.')}}else r.energy=Math.min(100,r.energy+dt*13);const forward=Math.max(stick.x,keys.has('ArrowRight')||keys.has('d')?1:0),brake=stick.x<-.2||keys.has('ArrowLeft')||keys.has('a');const target=brake?0:forward>.12?14*(r.slow>0?.36:1)*forward:0;r.speed+=(target-r.speed)*Math.min(1,dt*4);if(r.speed<.02)r.speed=0;const vertical=stick.y+(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);r.lane=Math.max(0,Math.min(2,r.lane+vertical*dt*2.2));r.distance=Math.min(levels[r.index].distance,r.distance+r.speed*dt);for(const h of r.hazards){if(!h.hit&&Math.abs(h.x-r.distance)<2.5&&Math.abs(h.lane-r.lane)<.42){h.hit=true;const airborne=r.glide||r.jump>.12;if(!airborne&&!(h.type==='water'&&r.swim)){r.slow=1.7;sounds.effect('trap');say(h.type==='water'?'Splash! A puddle slowed you down.':h.type==='bump'?'Bump! Keep going.':'Sticky mud! You’ll speed up again.')}else say(airborne?'Nicely cleared!':'Smooth swimming!',1.2)}}if(r.distance>=levels[r.index].distance){finish();return}updateHUD()}
function canvasSize(canvas){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=rect.width||600,h=rect.height||400;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return {c,w,h}}
function ellipse(c,x,y,rx,ry,fill){c.fillStyle=fill;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()}
function landscape(c,w,h,distance,theme){c.fillStyle=theme==='sky'?'#dceafa':'#e7f1d9';c.fillRect(0,0,w,h);ellipse(c,w*.8,h*.19,29,29,'#f5d776');for(let i=0;i<4;i++){const x=((i*w*.4-distance*1.3)%(w+140)+w+140)%(w+140)-70;ellipse(c,x,h*(.2+(i%2)*.1),39,15,'#fffdf1');ellipse(c,x-7,h*(.18+(i%2)*.1),20,20,'#fffdf1')}c.fillStyle=theme==='sky'?'#f6f8f1':'#c4d99f';c.beginPath();c.moveTo(0,h*.63);for(let x=0;x<=w+10;x+=10)c.lineTo(x,h*.48+Math.sin((x+distance*2)/160)*h*.12);c.lineTo(w,h);c.lineTo(0,h);c.fill();c.fillStyle=theme==='sky'?'#c7d9eb':'#a7c486';c.beginPath();c.moveTo(0,h*.7);for(let x=0;x<=w+10;x+=10)c.lineTo(x,h*.6+Math.sin((x+distance*3)/200+1)*h*.06);c.lineTo(w,h);c.lineTo(0,h);c.fill();if(theme==='lake'){c.fillStyle='#89c9d4';c.fillRect(0,h*.52,w,h*.1)}c.fillStyle='#f9f2d8';c.fillRect(0,h*.62,w,h*.32);if(theme==='rainbow'){['#eaaaaf','#f0cc7d','#afc9df'].forEach((colour,i)=>{c.fillStyle=colour;c.globalAlpha=.55;c.fillRect(0,h*(.62+i*.1067),w,h*.1067)});c.globalAlpha=1}c.strokeStyle='#b8b498';c.lineWidth=2;c.setLineDash([20,25]);c.lineDashOffset=distance*7;for(let i=1;i<3;i++){c.beginPath();c.moveTo(0,h*(.62+.32*i/3));c.lineTo(w,h*(.62+.32*i/3));c.stroke()}c.setLineDash([])}
function car(c,x,y,scale,options={}){c.save();c.translate(x,y);c.scale(scale,scale);if(options.tilt)c.rotate(options.tilt);if(options.kite){c.strokeStyle='#607452';c.lineWidth=2;c.beginPath();c.moveTo(0,-45);c.quadraticCurveTo(30,-95,14,-125);c.stroke();c.fillStyle='#f6d980';if(saved.kite==='diamond'){c.beginPath();c.moveTo(14,-165);c.lineTo(43,-137);c.lineTo(14,-105);c.lineTo(-15,-137);c.closePath();c.fill();c.stroke();c.beginPath();c.moveTo(14,-165);c.lineTo(14,-105);c.moveTo(-15,-137);c.lineTo(43,-137);c.stroke()}else{c.beginPath();c.arc(0,-121,62,Math.PI,0);c.closePath();c.fill();c.stroke();c.beginPath();c.moveTo(-62,-121);c.lineTo(0,-49);c.lineTo(62,-121);c.stroke()}}c.fillStyle=options.colour||colours[saved.colour];c.strokeStyle='#3c4a3b';c.lineWidth=3;c.beginPath();c.moveTo(-72,-18);c.quadraticCurveTo(-62,-79,-9,-77);c.quadraticCurveTo(44,-79,62,-24);c.lineTo(77,-17);c.quadraticCurveTo(85,-7,75,5);c.lineTo(-77,5);c.quadraticCurveTo(-88,-6,-72,-18);c.closePath();c.fill();c.stroke();c.fillStyle='#edf7e9';c.beginPath();c.moveTo(-54,-30);c.lineTo(-47,-52);c.quadraticCurveTo(-28,-66,-13,-65);c.lineTo(-13,-30);c.closePath();c.fill();c.stroke();c.beginPath();c.moveTo(2,-65);c.quadraticCurveTo(27,-65,40,-47);c.lineTo(49,-30);c.lineTo(2,-30);c.closePath();c.fill();c.stroke();c.beginPath();c.moveTo(-3,-24);c.lineTo(-3,0);c.moveTo(8,-20);c.lineTo(18,-20);c.stroke();c.fillStyle='#ffe59d';c.fillRect(69,-18,10,7);for(const wx of [-48,48]){c.save();c.translate(wx,4);c.rotate(options.spin||0);ellipse(c,0,0,20,20,saved.tyre==='flower'?'#ad6498':'#36473b');if(saved.tyre==='bumpy'){c.strokeStyle='#36473b';c.lineWidth=6;c.setLineDash([5,4]);c.beginPath();c.arc(0,0,20,0,Math.PI*2);c.stroke();c.setLineDash([])}ellipse(c,0,0,11,11,saved.tyre==='flower'?'#ffe18b':'#f5f1df');c.strokeStyle='#8a957c';c.lineWidth=3;c.beginPath();c.moveTo(-7,0);c.lineTo(7,0);c.moveTo(0,-7);c.lineTo(0,7);c.stroke();c.restore()}if(options.swim){c.strokeStyle='#65b5cf';c.lineWidth=7;c.beginPath();c.ellipse(0,12,88,12,0,0,Math.PI);c.stroke()}c.restore()}
function drawPreview(){if(screen!=='garage')return;const {c,w,h}=canvasSize($('preview'));landscape(c,w,h,0,'green');const scale=Math.min(w/260,h/255,2);ellipse(c,w*.5,h*.81,88*scale,10*scale,'#a8b88b');car(c,w*.5,h*.77,scale,{kite:true})}
function drawGame(){if(!race||screen!=='play')return;const {c,w,h}=canvasSize($('game')),r=race,l=levels[r.index],px=Math.min(7,w/95),carX=w*.23,scale=Math.min(1,w/490),roadY=lane=>h*(.675+lane*.105);landscape(c,w,h,r.distance,l.theme);for(const hazard of r.hazards){const x=carX+(hazard.x-r.distance)*px;if(x< -80||x>w+80)continue;const y=roadY(hazard.lane);if(hazard.type==='water'){ellipse(c,x,y,26,10,'#71c4d3');c.strokeStyle='#d8f4f4';c.beginPath();c.moveTo(x-12,y);c.quadraticCurveTo(x,y+5,x+12,y);c.stroke()}else if(hazard.type==='mud'){ellipse(c,x,y,24,10,'#aa8664');ellipse(c,x+7,y-3,5,2,'#d5b18b')}else{ellipse(c,x,y,22,9,'#c39c60');c.strokeStyle='#876d49';c.beginPath();c.arc(x,y,14,Math.PI,0);c.stroke()}}
const fx=carX+(l.distance-r.distance)*px;if(fx<w+50){c.strokeStyle='#405641';c.lineWidth=4;c.beginPath();c.moveTo(fx,h*.41);c.lineTo(fx,h*.94);c.stroke();for(let row=0;row<3;row++)for(let col=0;col<4;col++){c.fillStyle=(row+col)%2?'#fdf9ec':'#405641';c.fillRect(fx+col*10,h*.41+row*10,10,10)}}for(const b of [...r.rivals].sort((a,b)=>a.lane-b.lane)){const bx=carX+(b.distance-r.distance)*px;if(bx< -100||bx>w+100)continue;const by=roadY(b.lane);ellipse(c,bx,by+9,60*scale,7*scale,'#b3b68d');car(c,bx,by-12*scale,scale*.87,{colour:b.colour,spin:b.distance*.7});c.font='bold 11px system-ui';c.textAlign='center';c.fillStyle='#344b37';c.fillText(b.name,bx,by-85*scale)}const jumpHeight=r.jump>0?Math.sin(r.jump/.95*Math.PI)*55:0,altitude=r.glide?75:jumpHeight;ellipse(c,carX,roadY(r.lane)+9,64*scale,8*scale,'#b3b68d');car(c,carX,roadY(r.lane)-12*scale-altitude,scale,{kite:r.glide,swim:r.swim,spin:r.distance*.7,tilt:r.glide?-.08:0});if(r.slow>0){c.fillStyle='#654d39';c.font='bold 12px system-ui';c.textAlign='center';c.fillText('Slowed down',carX,roadY(r.lane)-98*scale)}if(r.distance<8&&!r.running&&$('overlay').hidden){c.fillStyle='#26382d';c.fillText('Hold right to drive',20,30)}}
function frame(now){const dt=lastTime?Math.min((now-lastTime)/1000,.05):0;lastTime=now;update(dt);sounds.engine(race?.running?race.speed:0);if(screen==='play'){drawGame();if(now>messageUntil)$('game-message').textContent=''}requestAnimationFrame(frame)}
window.addEventListener('resize',()=>{if(screen==='garage')drawPreview();else if(screen==='play')drawGame()});customise();renderLevels();requestAnimationFrame(frame);
})();
